name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *' # Run every morning at 7am UTC

jobs:
  nutest-tests:
    name: Run Nu-Test Tests

    permissions:
      checks: write
      pull-requests: write

    strategy:
      fail-fast: true
      matrix:
        version: ["0.101.0", "*", "nightly"] # Earliest supported, latest and nightly
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nushell Binary
        uses: hustcer/setup-nu@v3
        with:
          version: ${{ matrix.version }}

      - name: Test Nu-Test
        run: nu -c 'use nutest; nutest run-tests --reporter junit | save test-report.xml'

      # Second run currently required as we can only specify one reporter
      - name: Test Nu-Test
        run: nu -c 'use nutest; nutest run-tests --reporter terminal --fail'

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-report.xml

  nushell-tests:
    name: Run Nushell Tests

    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout Nushell
        uses: actions/checkout@v4
        with:
          repository: nushell/nushell
          ref: main
          path: nushell

      - name: Install Nushell Binary
        uses: hustcer/setup-nu@v3
        with:
          version: "*"

      - name: Test Nushell
        run: nu -c "use $GITHUB_WORKSPACE/nutest; nutest run-tests --reporter terminal --fail --path tests"
        working-directory: nushell/crates/nu-std
